---
  - name: Install list of packages
    action: 
       apt 
       update_cache=yes 
       cache_valid_time=84600
       pkg={{item}} 
       state=installed
    with_items:
    - unzip
    - build-essential
    - openssl
    - prelink
    - libssl-dev
    - libpcre++-dev
    - git 
    - libcurl4-openssl-dev
    sudo: true
    when: "{{is_ubuntu}}" 
  
  #- apt: upgrade=yes
